name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: script/generate
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: rebuild site